### ISSUE TITLE
Sample code of Picker class contains a typo

### ISSUE THREAD

**Issue by vondeetzen** [xamarin/Xamarin.Forms-api-docs#100]
There is a typo in the Picker class API documentation.

`Color.Fucshia` should be `Color.Fuchsia` according to the Color class.

As I did a quick grep of the project there are three more occurrences.

```
./docs/Xamarin.Forms/Color.xml:        <summary>Fucshia, the color that is represented by the RGB value #ff00ff.</summary>
./docs/Xamarin.Forms/Color.xml:        <summary>Fucshia, the color that is represented by the RGB value #ff00ff. Deprecated. See Remarks.</summary>
./docs/Xamarin.Forms/Picker.xml:            { "Blue", Color.Blue }, { "Fucshia", Color.Fucshia },
./docs/Xamarin.Forms/MasterDetailPage.xml:                    new NamedColor("Fucshia", Color.Fucshia),
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb6e410-cb78-d977-9df2-8e0d6c1cd8c9
* Version Independent ID: 5e8eb5b1-47b6-afd4-4054-3fb07ce2beed
* Content: [Picker Class (Xamarin.Forms)](https://docs.microsoft.com/en-gb/dotnet/api/xamarin.forms.picker?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Picker.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Picker.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
The spelling in the Picker docs has already been corrected; just opened PRs for the Colors docs and the MasterDetailPage.
