### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by voxoid0** [xamarin/Xamarin.Forms-api-docs#102]
What are the units and range? Is it 0-1 or in pixels? Does the max value mean the right side of the content is aligned with the left side of the scroll view or with the right side of the scroll view? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47bdb60-8bed-d311-a224-3b594447ce51
* Version Independent ID: 87f95f4e-cab7-b2b9-2060-ddcd2a79bf59
* Content: [ScrollView.ScrollX Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.scrollview.scrollx?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/ScrollView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ScrollView.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
