### ISSUE TITLE
caching strategy =Recycle element issue

### ISSUE THREAD

**Issue by Bharathsimhadri** [xamarin/Xamarin.Forms-api-docs#103]
caching strategy =Recycle element causing ui issues ,the next viewcells poperties are not updating properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8804ce-01ef-5134-926d-0bd21f66fa0d
* Version Independent ID: cb82ba5a-b207-61b2-07e6-85bb569143ce
* Content: [ListViewCachingStrategy Enum (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listviewcachingstrategy?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ListViewCachingStrategy.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ListViewCachingStrategy.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Bharathsimhadri** [comment]
![Screenshot_1562937924](https://user-images.githubusercontent.com/45058509/61131350-aa61bf00-a4d6-11e9-962e-0d53102c93ec.png)
![Screenshot_1562937927](https://user-images.githubusercontent.com/45058509/61131364-b2216380-a4d6-11e9-944f-cf5738f7591c.png)

see the above two images ,

**Comment by Bharathsimhadri** [comment]
the text in the first image's 1st row,second column not updated completely,the second image is view screen  
that displays on clicking list view

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
