### ISSUE TITLE
Difference between BorderColor and OutlineColor

### ISSUE THREAD

**Issue by titonton** [xamarin/Xamarin.Forms-api-docs#104]
What is the difference between the two properties? In the example the OutlineColor is mentioned but BorderColor is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92d840b9-b788-23aa-8918-41fd9eb8c907
* Version Independent ID: 053eaf42-3c76-f15e-62b8-d9dab8dfef6b
* Content: [Frame Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.frame?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Frame.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Frame.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
They both do the same thing. OutlineColor is the old (pre 3.0.0) name for the property. It is marked as Obsolete. BorderColor is what you should use instead.

**Comment by titonton** [comment]
@hartez Okay Thanks. yea BorderColor makes a bit more sense. Thanks for the clarification
