### ISSUE TITLE
Page.IsBusy does not show indicator on Android

### ISSUE THREAD

**Issue by himensuthar** [xamarin/Xamarin.Forms-api-docs#105]
this property does not show global activity indicator on Android Xamarin Form. Please suggest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf418dd-124c-eb8f-fd83-4652d0ca77b6
* Version Independent ID: df0c0870-7b07-9236-5449-e7b90c5b63f3
* Content: [Page.IsBusy Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.Page.IsBusy?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by PureWeen** [comment]
I'm closing this as it looks like the details of this issue is captured here
https://github.com/xamarin/Xamarin.Forms/issues/7274
