### ISSUE TITLE
Enum does not match description on another page in the documentation

### ISSUE THREAD

**Issue by GZidar** [xamarin/Xamarin.Forms-api-docs#107]
The list of options described on the page linked below includes options that are not defined in this enum.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#named-font-sizes

Which list is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219a061c-dc79-5987-8ffd-6b65bc9e338d
* Version Independent ID: f084da92-2a66-486f-8a0d-19e3c733c688
* Content: [NamedSize Enum (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.namedsize?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/NamedSize.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/NamedSize.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by KUTlime** [comment]
The other one (with more options).

**Comment by StephaneDelcroix** [comment]
both list contains 10 elements. I assume it has been fixed since.
