### ISSUE TITLE
Keyboards Instances

### ISSUE THREAD

**Issue by jveltd** [xamarin/Xamarin.Forms-api-docs#109]
The Keyboard instances are listed here but what do they actually look like on iOS / Android?  What numerics / text are displayed?  Some examples of what the keyboards look like would be handy...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964097f9-62ef-eead-bee7-f7a5ec2ecc90
* Version Independent ID: 8b449255-133d-c04d-9f17-fe9b0daaf1e5
* Content: [Keyboard Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.keyboard?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Keyboard.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Keyboard.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
