### ISSUE TITLE
Screenshots or at least a brief description useful

### ISSUE THREAD

**Issue by robiharid** [xamarin/Xamarin.Forms-api-docs#121]
useless page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6ad26b-508d-29d9-5a9b-3f95ffda9bec
* Version Independent ID: 6a5f60a1-f736-ced0-4d84-9a6a0ba9c1bb
* Content: [Keyboard.Chat Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.keyboard.chat?view=xamarin-forms#Xamarin_Forms_Keyboard_Chat)
* Content Source: [docs/Xamarin.Forms/Keyboard.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Keyboard.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
