### ISSUE TITLE
This page not helpful

### ISSUE THREAD

**Issue by warwlf** [xamarin/Xamarin.Forms-api-docs#122]
Could each of the keyboard pages have an image for the support OSes or at least a description of what makes this a text keyboard as opposed to chat, numeric.  I suggest perhaps a chart and list what could be on a keyboard and then for each type of keyboard, check if that is present of the given keyboard.  This chart could be used on the main Keyboard class page making viewing these pages unnecessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e0411e-b2b4-b3a7-aa51-fbb6005bbd3d
* Version Independent ID: fc220f1a-2eb7-6db4-b551-fe4f3c91d3a5
* Content: [Keyboard.Text Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.keyboard.text?view=xamarin-forms#Xamarin_Forms_Keyboard_Text)
* Content Source: [docs/Xamarin.Forms/Keyboard.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Keyboard.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
