### ISSUE TITLE
What is "Name"?

### ISSUE THREAD

**Issue by LJ9999** [xamarin/Xamarin.Forms-api-docs#131]
How is label transformed into &lt;Label...? This makes no sense with a context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aacf32d-5e13-edec-f5a6-5fcdd4c2abff
* Version Independent ID: 8073558b-5871-f827-8a2a-e2e980ba2cb7
* Content: [BindableObject.SetBinding(BindableProperty, BindingBase) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.bindableobject.setbinding?view=xamarin-forms#Xamarin_Forms_BindableObject_SetBinding_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindingBase_)
* Content Source: [docs/Xamarin.Forms/BindableObject.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/BindableObject.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by objdesignlabs** [comment]
Represents the spefoc
