### ISSUE TITLE
Grouping Properties are missing

### ISSUE THREAD

**Issue by ackava** [xamarin/Xamarin.Forms-api-docs#138]
As per this page, https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/grouping CollectionView supports grouping. However this class does not display any such properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40f04ce2-50bb-08d8-c0aa-b91f69d50841
* Version Independent ID: 0d6ce5c9-14d8-3219-05a4-735fe85bede7
* Content: [CollectionView Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.collectionview?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/CollectionView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/CollectionView.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @ackava - I'm seeing `IsGrouped`, `GroupHeaderTemplate`, and `GroupFooterTemplate` all listed under the Properties section of the CollectionView Class API. (It's possible these changes were made after you submitted this issue as well) 
Is this what you were getting at, or are there other properties you see missing?

**Comment by ackava** [comment]
@rachelkang I can see it now.
