### ISSUE TITLE
Missing word in the Remarks section

### ISSUE THREAD

**Issue by JohnHunterPartholan** [xamarin/Xamarin.Forms-api-docs#139]
The phrase "over the scope of the that they supply" does not make sense, it seems like there is a word missing between "the" and "that".  Also, it might be useful to provide a clearer explanation of the scope, e.g. project or solution wide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2b04b7-a740-b640-804a-c0de5484577e
* Version Independent ID: 6e899f5c-0408-49c1-3c05-662f931facb0
* Content: [ResolutionGroupNameAttribute Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.resolutiongroupnameattribute?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/ResolutionGroupNameAttribute.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ResolutionGroupNameAttribute.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
