### ISSUE TITLE
So how can this be used?

### ISSUE THREAD

**Issue by dafemec** [xamarin/Xamarin.Forms-api-docs#140]
So how can this be used?  This help borders on useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69416020-918a-db35-33d0-0d3ae094fe12
* Version Independent ID: 40b15572-b383-b6be-6366-bac41061e652
* Content: [ListView.ItemTapped Event (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.ListView.ItemTapped?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ListView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ListView.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @dafemec - you may be able to find the information you're looking for here: https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/listview/interactivity hope this helps!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
