### ISSUE TITLE
So how can this be used? This help borders on useless.

### ISSUE THREAD

**Issue by dafemec** [xamarin/Xamarin.Forms-api-docs#143]
So how can this be used? This help borders on useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97d45f7-86ac-10bf-85d0-f2ecf562b751
* Version Independent ID: 836a9078-831b-0bc4-1e7e-b5ac466939b4
* Content: [OnPlatformExtension Class (Xamarin.Forms.Xaml)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.xaml.onplatformextension?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Xamarin.Forms.Xaml.OnPlatformExtension);k(VS.XamlEditor)%26rd%3Dtrue&view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.Xaml/OnPlatformExtension.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.Xaml/OnPlatformExtension.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by aharwood2** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/markup-extensions/consuming#onplatform

**Comment by StephaneDelcroix** [comment]
This API is marked "For Internal Use Only", and as such, it's ok if the doc is lacking
