### ISSUE TITLE
So how can this be used? This help borders on useless.

### ISSUE THREAD

**Issue by dafemec** [xamarin/Xamarin.Forms-api-docs#144]
So how can this be used? This help borders on useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bba293e-da7c-fe18-5f6b-5c6f912ceae0
* Version Independent ID: 330b7b7a-0462-9f0d-162b-a3c59d0d83ac
* Content: [BindingExtension.StringFormat Property (Xamarin.Forms.Xaml)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.xaml.bindingextension.stringformat?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Xamarin.Forms.Xaml.BindingExtension.StringFormat);k(VS.XamlEditor)%26rd%3Dtrue&view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.Xaml/BindingExtension.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.Xaml/BindingExtension.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by StephaneDelcroix** [comment]
This API is marked as "For Internal Use", the lack of doc is OK
