### ISSUE TITLE
Color doc

### ISSUE THREAD

**Issue by GioviQ** [xamarin/Xamarin.Forms-api-docs#146]
ffffff00 is yellow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c80d0c2-74cf-9c07-81b8-21ef5e37becc
* Version Independent ID: 5cfa172b-02c5-0550-96a8-03db85c63109
* Content: [Color.Transparent Field (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.color.transparent?view=xamarin-forms#commenti)
* Content Source: [docs/Xamarin.Forms/Color.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Color.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @GioviQ! #ffffff00 is an 8-digit hex code, which means the last 2 digits represent the opacity.
In this case, the 00 indicates that the color is fully transparent. Let me know if you think I'm misunderstanding or would like further clarification!

**Comment by GioviQ** [comment]
When I tried that color (11/30/2019) in Xamarin.Forms it worked as #aarrggbb and not as #rrggbbaa as explained.

**Comment by rachelkang** [comment]
@GioviQ yes, you're totally right - apologies for the misunderstanding and confusion. Will fix this shortly!
Here's some more info on [Colors in Xamarin.Forms](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/colors)
