### ISSUE TITLE
Documentation on how to use appears to be missing.

### ISSUE THREAD

**Issue by AntRemo** [xamarin/Xamarin.Forms-api-docs#147]
I can't seem to get this feature to work and I also can't find any documentation on it. 
Please add. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f08b535f-a3bd-a241-e67e-7e770246b6b6
* Version Independent ID: 853b3578-a5f0-6f26-3800-3f8cdc7dde37
* Content: [Page.SetPrefersHomeIndicatorAutoHidden Method (Xamarin.Forms.PlatformConfiguration.iOSSpecific)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.iosspecific.page.setprefershomeindicatorautohidden?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
