### ISSUE TITLE
Still missing important information.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms-api-docs#149]
This documentation does not indicate whether `BeginInvokeOnMainThread()` blocks until it completes. I previously reported this and it was closed because, "A version that uses a Task to indicate completion is in preview". That's cute, but it doesn't change that *this* page does not document the behavior of the method. The documentation should, at minimum,  note this method does not block. It could go further and suggest using a TaskCompletionSource if you need that support, but that's just "going the extra mile".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e06d33-fcc4-e4f8-103c-fb286df48c29
* Version Independent ID: 774d794a-04a4-2d51-07d3-77f20157dfbc
* Content: [Device.BeginInvokeOnMainThread(Action) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by SittenSpynne** [comment]
Also for the record:

An asynchronous method that begins its name with "Begin" should accept an `IAsyncResult`, this is the proper original .NET asynchronous pattern. If this is intended to be asynchronous via tasks or events, it should be named "InvokeOnMainThreadAsync()`. But it doesn't return a task or use an event so it's basically violating every possible API design guideline.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
