### ISSUE TITLE
What does this actually do?

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms-api-docs#151]
As far as I can tell, setting a Pin's type to these different values makes no difference in the Pin's behavior. Is that wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e444e0b5-20ee-68a4-5f6f-6035bfae4c5f
* Version Independent ID: 01afee4c-0f03-1ace-ab5d-3fdf49f7b12e
* Content: [PinType Enum (Xamarin.Forms.Maps)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps.pintype?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms.Maps/PinType.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.Maps/PinType.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mattleibow** [comment]
Looking at the code, it doesn't actually seem to do anything... Not sure why since it has been there since the beginning and has no committer/comments.
I'll try poke around some more and figure it out.

**Comment by mattleibow** [comment]
Looking around, it never did anything inside forms. It could be that it was useful for 3rd party libraries with custom renderers?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
