### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by dafemec** [xamarin/Xamarin.Forms-api-docs#154]
How do you use this?  An example would be helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc8be77-c0e4-27a0-af63-bf942137fcb0
* Version Independent ID: a9c4e8a3-e09b-7464-ae81-c3e32a42270e
* Content: [SwipeGestureRecognizer Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.swipegesturerecognizer?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/SwipeGestureRecognizer.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/SwipeGestureRecognizer.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Duefectu** [comment]
+1: Put some sample, please

**Comment by hartez** [comment]
@dafemec An example is available in the [Application Fundamentals section of the docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/swipe).
