### ISSUE TITLE
Documentation for Binding.UpdateSourceEventName property

### ISSUE THREAD

**Issue by mbalous** [xamarin/Xamarin.Forms-api-docs#158]
This property of `Binding` works fine on UWP & Android, but **doesn't** seem to **work** on iOS.

Furhermore it is missing any documentation and for some reason is marked "_For internal use_". It is unclear is usage of this property is undesired and could lead to sime issues or if it is fine to use it. 

My suggestion is to provide more information about this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26556b39-e58b-5f20-169d-41643d41e9c3
* Version Independent ID: de929a2b-7132-b051-1f12-5f9ef164b895
* Content: [BindingExtension.UpdateSourceEventName Property (Xamarin.Forms.Xaml)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.xaml.bindingextension.updatesourceeventname?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Xamarin.Forms.Xaml.BindingExtension.UpdateSourceEventName);k(VS.XamlEditor);k(SolutionItemsProject);k(SolutionItemsProject)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.Xaml/BindingExtension.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.Xaml/BindingExtension.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
