### ISSUE TITLE
 Device.OpenUri is Deprecated and alternative doesn't work on ios

### ISSUE THREAD

**Issue by musicm122** [xamarin/Xamarin.Forms-api-docs#159]
Device.OpenUri 
https://github.com/xamarin/Xamarin.Forms/issues/8552

And the recommended alternatives from the Xamarin essentials libs aren't going to being accepted from apple. 

Launcher.OpenAsync 

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

https://github.com/xamarin/Xamarin.Forms/issues/7323

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f68e9bd-8443-2e15-53b2-d735fc68a2a6
* Version Independent ID: 8eaa7aa9-b895-8bea-193c-da58340230da
* Content: [Device.OpenUri(Uri) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.openuri?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by PureWeen** [comment]
@musicm122 I'm closing this as it looks like the issues you are referencing have been resolved

If the APIs aren't working please log an issue on the Forms or Essentials repositories
https://github.com/xamarin/Xamarin.Forms
https://github.com/xamarin/Essentials
