### ISSUE TITLE
This API is now obsolete.

### ISSUE THREAD

**Issue by WDCoates** [xamarin/Xamarin.Forms-api-docs#166]
If the API is now obsolete either point to the replacement method or the new recommended pages. Would that be so hard!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526d1905-8c2e-81c4-7165-1fb305ca892f
* Version Independent ID: 0940041b-e0aa-7c6e-0884-2e3c646ddf7b
* Content: [Device.OnPlatform Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.onplatform?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by StephaneDelcroix** [comment]
it's in plain text in the Obsolete message

>[System.Obsolete("OnPlatform<> (generic) is obsolete as of version 2.3.4. Please use 'switch (Device.RuntimePlatform)' instead.")]
