### ISSUE TITLE
Default for this setting

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms-api-docs#170]
This page should list what the default is for this setting. Likewise for all the platform-specific settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf31754-688c-b812-a36c-bb0b086d591d
* Version Independent ID: bafac6e8-158a-fe53-aab3-6d106684de7b
* Content: [Application.SetEnableAccessibilityScalingForNamedFontSizes Method (Xamarin.Forms.PlatformConfiguration.iOSSpecific)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.iosspecific.application.setenableaccessibilityscalingfornamedfontsizes?view=xamarin-forms#Xamarin_Forms_PlatformConfiguration_iOSSpecific_Application_SetEnableAccessibilityScalingForNamedFontSizes_Xamarin_Forms_IPlatformElementConfiguration_Xamarin_Forms_PlatformConfiguration_iOS_Xamarin_Forms_Application__System_Boolean_)
* Content Source: [docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Application.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.PlatformConfiguration.iOSSpecific/Application.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
