### ISSUE TITLE
Unclear definition

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms-api-docs#171]
I think it's not 100% clear, if this property should be set on implicit or explicit style. Could you provide us some example?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab26fc4-1df0-a929-0d73-b3f61281c083
* Version Independent ID: d6ae5327-289a-5a40-0c07-99a38753b84e
* Content: [Style.CanCascade Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.style.cancascade?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Xamarin.Forms.Style.CanCascade);k(VS.XamlEditor)%26rd%3Dtrue&view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Style.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Style.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by docen67** [comment]
i wonder the same thing.

**Comment by viktorszekeress** [comment]
According to this:
https://github.com/xamarin/Xamarin.Forms-api-docs/issues/39

`CanCascade` should be applied to explicit style.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
