### ISSUE TITLE
"Applies to" could be improved.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms-api-docs#174]
I have one project where this method is available and another project where it is not available. They *appear* to be using the same version of Xamarin Forms, but it'd be nice if this documentation indicated the first version to provide this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f701a57-a87b-e015-b376-4e46c170a838
* Version Independent ID: 60d7513d-1192-46a8-fafd-a4c021eec4ef
* Content: [Device.InvokeOnMainThreadAsync Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.invokeonmainthreadasync?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by RaymondEllis** [comment]
Looks like this method was introduced in 4.1.0: https://github.com/xamarin/Xamarin.Forms/pull/5028
But had a bug that rendered it unusable until 4.2.0: https://github.com/xamarin/Xamarin.Forms/issues/6705

**Comment by mattleibow** [comment]
@Redth this is basically because we only ever have a single version of the docs. We might need to investigate doing the multi-version for the major.minor at least. This way the methods can at least show when they were added.

**Comment by joelmartinez** [comment]
@mattleibow the frameworkalternate stuff only applies to "things below types and members" like attributes and parameter names (to oversimplify it :P )... so type and member inclusion in a given moniker/framework is indicated by the FrameworkIndex files:  
https://github.com/mono/SkiaSharp-API-docs/tree/master/SkiaSharpAPI/FrameworksIndex

But yeah, if this lib shifts to using "frameworks mode", as you're doing with skia sharp, then all the information should definitely be there. Unfortunately as you're talking about, looks like overload groups don't get any differentiation here, so I would recommend working with the reference PM @mimisasouvanh to create a customer suggestion (which puts it on the work stack for consideration/prioritization, etc)

**Comment by mattleibow** [comment]
I'm going to close this for now since there is nothing this repo can do. I have put in a customer request for a better layout of the page or something better than I can think of.
Hopefully, as soon as things are implemented, magic will happen.

Internal docs request: https://dev.azure.com/ceapex/Engineering/_workitems/edit/325816/
