### ISSUE TITLE
OnAppeared

### ISSUE THREAD

**Issue by zdananic23** [xamarin/Xamarin.Forms-api-docs#179]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2969e5f-e192-94e3-223a-e9f354503104
* Version Independent ID: 190a6979-1884-ec70-a9b4-a8e41b5a4423
* Content: [MasterDetailPage.OnAppearing Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.masterdetailpage.onappearing?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/MasterDetailPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/MasterDetailPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by PureWeen** [comment]
@zdananic23 Can you explain more about the issue with the docs you are seeing? 

If this is an issue with Xamarin.Forms or an enhancement request please log your feedback here
https://github.com/xamarin/Xamarin.Forms

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
