### ISSUE TITLE
Add information about security

### ISSUE THREAD

**Issue by KirillBorunov** [xamarin/Xamarin.Forms-api-docs#180]
Is it OK to store sensitive information (tokens, etc.) using this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8931b2d9-6ee8-a16d-5cd3-679469e28616
* Version Independent ID: 483899e4-e37d-e8b0-7800-a08c5d27044b
* Content: [Application.Properties Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.properties?view=xamarin-forms#Xamarin_Forms_Application_Properties)
* Content Source: [docs/Xamarin.Forms/Application.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Application.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
I wouldn't recommend it. If you need secure storage, take a look at the Secure Storage feature of Essentials: https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fxamarin-forms&tabs=android

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
