### ISSUE TITLE
How to read cookies on Tizen

### ISSUE THREAD

**Issue by hadihashem** [xamarin/Xamarin.Forms-api-docs#182]
Hello
This document mentions clearly that WebView.EvaluateJavaScriptAsync is not implemented on Tizen.NET plateform
Is there another way to execute JavaScript with a return value on Tizen.NET plateform? particularly to read the content of a cookie
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7ee7d-7e75-a9d5-34cd-c21b884dcfa2
* Version Independent ID: d079de06-85be-3063-44fb-fe6bb297aa70
* Content: [WebView.EvaluateJavaScriptAsync(String) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webview.evaluatejavascriptasync?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/WebView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/WebView.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
