### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by LadderLogic** [xamarin/Xamarin.Forms-api-docs#183]
Empty ritualistic documents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c8ef97-45df-7e93-c61e-ffa669a6645f
* Version Independent ID: f1da66f0-8b19-76b6-e6fe-3bcb2afe084c
* Content: [FlyoutDisplayOptions Enum (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.flyoutdisplayoptions?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/FlyoutDisplayOptions.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/FlyoutDisplayOptions.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by samhouts** [comment]
There is information there. These also drive the Intellisense in Visual Studio.
