### ISSUE TITLE
So instead use...?

### ISSUE THREAD

**Issue by jefffhaynes** [xamarin/Xamarin.Forms-api-docs#184]
Maybe update to point in the right direction for alternatives

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bacef1b6-229a-1ef4-505d-03bb11267532
* Version Independent ID: 03d2dee9-0113-a424-236d-42811fc1323a
* Content: [Page.DisplayPromptAsync Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.displaypromptasync?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by amp64** [comment]
Maybe it is just the first overload that is deprecated? Not obvious from this page.

**Comment by Nosegoo** [comment]
DisplayAlert has an overload that allows you to Yes/No options.

**Comment by mattleibow** [comment]
It is just the first item that is obsolete. This probably needs some sort of better page layout to not have the first item the obsolete one.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
