### ISSUE TITLE
This functionality don't work

### ISSUE THREAD

**Issue by RiccardoDori** [xamarin/Xamarin.Forms-api-docs#186]
// Summary:
        //     To be added.
        //
        // Remarks:
        //     To be added.
        public bool IsEnabled { get; set; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cc9cf46-559e-8994-a2e5-7c55421f0971
* Version Independent ID: f07d00ff-2db2-f0fb-250f-485d6ad63ea7
* Content: [BaseShellItem.IsEnabled Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.baseshellitem.isenabled?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/BaseShellItem.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/BaseShellItem.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by RiccardoDori** [comment]
I currently refer to packages\xamarin.forms\4.4.0.991265\lib\netstandard2.0\Xamarin.Forms.Core.dll

**Comment by PureWeen** [comment]
@RiccardoDori can you please log an issue with a reproduction here?

https://github.com/xamarin/Xamarin.Forms
