### ISSUE TITLE
Why can we only use master detail page as app root page?

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms-api-docs#188]
As the documentation says "Developers should **only** use master detail pages as the application root page" I raised an enhancement request for being able to use MasterDetailPage in **split mode** as Tabs for an app which has a TabbedPage as the root page. My confusion is that this already seems to be supported and works fine on iOS, Android, UWP and Mac Tablet/Desktop, but pursuing this route is risky as it contradicts the documentation. 

Using MasterDetailPage in flyout mode (with hamburger menu) as a root page only makes sense to me but I can see use cases for using it as a child page in splitmode to make use of extra space on tablet and Desktop.  Are there exceptions where it's ok to use MasterDetailPage as a child page? Could the documentation clarify what problem I could face in the future? It works ok for now so not sure my enhancement request is even needed if the documentation is updated to align?  https://github.com/xamarin/Xamarin.Forms/issues/10262

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de55d44a-3eca-f5f4-70fd-fbf7d8a6e052
* Version Independent ID: dcc6ec0e-b849-ff1a-6915-339ce503baf8
* Content: [MasterDetailPage Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.masterdetailpage?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/MasterDetailPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/MasterDetailPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
