### ISSUE TITLE
Given the ultra-complex layout system maybe document public methods

### ISSUE THREAD

**Issue by jefffhaynes** [xamarin/Xamarin.Forms-api-docs#190]
Just a thought

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b22f09-8853-06aa-c2b9-73e2a7320235
* Version Independent ID: d86b7814-9b44-0778-1794-528afe209a2c
* Content: [VisualElement.NativeSizeChanged Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.nativesizechanged?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
