### ISSUE TITLE
NavigationPage.SetHasNavigationBar(this, false); Does not work on Android at least

### ISSUE THREAD

**Issue by EricOuellet2** [xamarin/Xamarin.Forms-api-docs#191]
NavigationPage.SetHasNavigationBar(this, false); Does not work on Android at least

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b14b18f-9435-c2fe-5b4e-66c960e0cb1b
* Version Independent ID: 92877a1e-3451-5456-582c-ac127990e940
* Content: [NavigationPage.SetHasNavigationBar(BindableObject, Boolean) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.sethasnavigationbar?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/NavigationPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/NavigationPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by luislema79** [comment]
Also, it doesn't work on iOS.

**Comment by luislema79** [comment]
You need to have it in every page for it to work:

public Main()
        {
            InitializeComponent();
            NavigationPage.SetHasNavigationBar(this, false);
        }

**Comment by PureWeen** [comment]
Hello @EricOuellet2 this repository is primarily for issues with the docs

If you are having an issue with an API can you please log your issue here https://github.com/xamarin/Xamarin.Forms with a reproduction so that we can fix? or help?
