### ISSUE TITLE
Xamarin.Forms API docs are broken

### ISSUE THREAD

**Issue by Torkell** [xamarin/Xamarin.Forms-api-docs#197]
The Xamarin.Forms API docs don't display correctly. The contents tree on the left is missing and above the page header the first line of the documentation is repeated with what looks like a broken HTML tag. The Applies To section is empty as well.

Some example screenshots (using Waterfox Classic 2020.06, though I've checked and they're also broken in Microsoft Edge):

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms?view=xamarin-forms
![image](https://user-images.githubusercontent.com/5759128/84026228-da367280-a984-11ea-84dc-6e9cc91e8c07.png)

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.absolutelayout?view=xamarin-forms
![image](https://user-images.githubusercontent.com/5759128/84026280-f20df680-a984-11ea-923c-cef01b2affdb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcw==
* Version Independent ID: L2VuLXVzL2RvdG5ldC9hcGkveGFtYXJpbi5mb3Jtcw==
* Content: [Xamarin.Forms Namespace](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms?view=xamarin-forms)
* Content Source: [docs/ns-Xamarin.Forms.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/ns-Xamarin.Forms.xml)

**Comment by samhouts** [comment]
This has been fixed. Thanks!
