### ISSUE TITLE
Does not work as advertised on UWP

### ISSUE THREAD

**Issue by BOSnooneTON** [xamarin/Xamarin.Forms-api-docs#215]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f1bff9-a66a-04b5-ee7a-4118bb3e07ba
* Version Independent ID: bab009dc-7ed0-b689-0c66-3c4473c1edd0
* Content: [Page.DisplayAlert Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.displayalert?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
@BOSnooneTON Can you please elaborate?

**Comment by PureWeen** [comment]
Hello @BOSnooneTON since we haven't heard from you in a while I'm going to close this issue

If you are still seeing issues on UWP can you log a bug here please https://github.com/xamarin/Xamarin.Forms
