### ISSUE TITLE
This page could use a sample

### ISSUE THREAD

**Issue by hebronwatson** [xamarin/Xamarin.Forms-api-docs#220]
Visual Studios does not autocomplete the delegate signature for writing this callback, so it would be useful to have an example of the signature for the callback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc85833-5f78-c5cd-464c-32264d1459e1
* Version Independent ID: ce036890-73ab-031a-dd5e-934b2f17c70e
* Content: [Map.MapClicked Event (Xamarin.Forms.Maps)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps.map.mapclicked?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms.Maps/Map.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms.Maps/Map.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
