### ISSUE TITLE
Doesn't say how to reset it

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms-api-docs#221]
If you have assigned a width or height request and want to clear it later, this page doesn't specify what value to set it to. Is it 0, -1, anything less than or equal to zero?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe156cf-8d05-bc7c-76bf-6b4f4854ca06
* Version Independent ID: 4405862c-64f5-55ce-1580-d873699a7360
* Content: [VisualElement.WidthRequest Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.widthrequest?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by StephaneDelcroix** [comment]
just like any other value, use ClearValue(). I don't think we'll start adding how to reset a property to its default on each type and props

**Comment by Tommigun1980** [comment]
> just like any other value, use ClearValue(). I don't think we'll start adding how to reset a property to its default on each type and props

@StephaneDelcroix That’s not what I meant.

I need to know what is the “not set” value. Isn’t the ONE place to find this out in Xamarin docs the ACTUAL width and height property doc? What do you mean with every place, this is where it is implemented and where it should say stuff like that.

So I repeat - when width/height has been set - and to thrn clear it say in XAML, should it be set to 0, to -1 or what?

And if this information does not belong in the actual property definitions for width and height please advice on where it is, and maybe consider adding it to here as this is where width and height are defined.

**Comment by StephaneDelcroix** [comment]
What I meant is that the actual value used as marker for non-set is not important. clear the value, using ClearValue, or set it to WidthRequestProperty.DefaultValue.

This isn't specific to WidthRequest, and doesn't deserve a special mention in the docs
