### ISSUE TITLE
Need to make clear whether app code is responsible for disposing stream, or whether XF does it

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms-api-docs#269]
This page needs to make explicit whether the app code needs to dispose the Stream used, or whether Xamarin.Forms disposes it automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94d3b46-a1b4-7389-e16f-c33ef75a8f4b
* Version Independent ID: f3a1912c-78bd-6ac4-81ad-19c3e877c15a
* Content: [ImageSource.FromStream(Func&lt;Stream&gt;) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.imagesource.fromstream?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ImageSource.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ImageSource.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
