### ISSUE TITLE
tell us exactly what needs to be in the code behind signature to catch the event

### ISSUE THREAD

**Issue by TomCJones** [xamarin/Xamarin.Forms-api-docs#270]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2109f73-02b7-149f-6317-c88fa3476735
* Version Independent ID: f8ab3793-5cad-bba3-16d2-9050708a698e
* Content: [Entry.Completed Event (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.entry.completed?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Entry.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Entry.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @TomCJones - I believe the information you're looking for can be found here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#completed but please let us know if you have further feedback / if there's anything more that you might be looking for!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
