### ISSUE TITLE
Callback Parameter Details

### ISSUE THREAD

**Issue by mohanasra** [xamarin/Xamarin.Forms-api-docs#271]
[Enter feedback here]
It would be great to know details about event parameters for callback.
Auto generated callbacks have parameters object sender, EventArgs e.
However, there is no comprehensive documentation about these parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f31f2ca-dbc4-35c7-9955-dbb7091604c0
* Version Independent ID: 95fd0c88-690b-453c-657f-66b7baa85898
* Content: [Page.Appearing Event (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.appearing?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @mohanasra - thanks for submitting this issue!
The page you submitted has a link to our docs on [EventHandler](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler?view=net-5.0) which includes info on those parameters. I'm assuming this is what you were looking for, but if you have further feedback/suggestions, please do share!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
