### ISSUE TITLE
OnPaint

### ISSUE THREAD

**Issue by joepuhich** [xamarin/Xamarin.Forms-api-docs#272]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb3ffbc-3f8e-55aa-b29e-3add44dc3444
* Version Independent ID: 1efb003e-9777-36d7-5e3a-54fb8f3f4597
* Content: [Layout.InvalidateLayout Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.Layout.InvalidateLayout?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Layout.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Layout.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @joepuhich - would you mind elaborating? Would love to have a clearer understanding of your feedback on this page.

**Comment by joepuhich** [comment]
When I use C# System.Windows.Forms I am able to put a character to screen
using OnPaint.
I have been trying to put a character to the screen using OnPaint in c#
Xamarin.Android mobile.
Using Invalidate() to start OnPaint() I'm not able to compile  C# code.
when I use OnDraw to put a character to the screen, I get the same results
as OnPaint .
Every code I write outside C# System.Windows.Forms get the same results as
OnPaint in Xamarin.Android.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
