### ISSUE TITLE
,kl

### ISSUE THREAD

**Issue by lass3ad00** [xamarin/Xamarin.Forms-api-docs#273]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb403b5d-dd95-2c8f-23f7-65af9d76cb5e
* Version Independent ID: 3aea5b61-0cf5-8e5e-04f5-0ddf11b3818f
* Content: [Page.OnAppearing Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.onappearing?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @lass3ad00 - would you mind elaborating? Would love to have a clearer understanding of your feedback on this page.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
