### ISSUE TITLE
Xamarin.Forms.Maps namespace: missing UWP example

### ISSUE THREAD

**Issue by stewa11** [xamarin/Xamarin.Forms-api-docs#274]
WHERE IS THE UWP EXAMPLE??? IT APPEARS TO BE MISSING
thanks
Stew
[Enter feedback here]
WHERE IS THE UWP EXAMPLE??? IT APPEARS TO BE MISSING
thanks
Stew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf9d0ac3-9696-8980-83c5-cf00feb332f5
* Version Independent ID: 81c7bcd0-f2e7-c68f-3699-f09005c5238f
* Content: [Xamarin.Forms.Maps Namespace](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps?view=xamarin-forms)
* Content Source: [docs/ns-Xamarin.Forms.Maps.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/ns-Xamarin.Forms.Maps.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @stewa11 - thank you for your feedback. I hope you find these links on XF Maps x UWP usage helpful:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup#map-initialization
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup#universal-windows-platform
https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps/WorkingWithMaps/WorkingWithMaps.UWP

If you're facing an issue that you don't see addressed in these links, please do share more details! Thank you :)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
