### ISSUE TITLE
Wrong description of fields of "FlyoutItem Class"

### ISSUE THREAD

**Issue by shawyunz** [xamarin/Xamarin.Forms-api-docs#275]
Hi, I found this [issue](https://github.com/xamarin/Xamarin.Forms-api-docs/issues/212) was supposed to be fixed from [this PR](https://github.com/xamarin/Xamarin.Forms-api-docs/pull/243).
But the page looks the same as before? And the description of "LayoutStyle" field is incorrect.

![image](https://user-images.githubusercontent.com/43285754/102841097-2781b980-4469-11eb-97f7-31131cc9ce2a.png)

Cheers,
Shaw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a66fa302-1f37-7572-682a-56ffe940d51d
* Version Independent ID: d377ada1-cfc7-2595-a402-b5579945d037
* Content: [FlyoutItem Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.flyoutitem?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/FlyoutItem.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/FlyoutItem.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @shawyunz - thanks for bringing this to our attention! We're taking a closer look at this issue.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
