### ISSUE TITLE
Remarks Developers should only call this method before Xamarin.Forms is initialized.

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms-api-docs#277]
why there is Remarks like that? Device.SetFlags can be called in the shared project i think. Forms.Init happens within the platform project. isn't that a conflict?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263aad2d-ec22-edfc-2c58-093d7007f7c2
* Version Independent ID: bc14b5e1-60d9-8849-0263-bc0ce8218bcb
* Content: [Device.SetFlags(IReadOnlyList&lt;String&gt;) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.setflags?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @EmilAlipiev - thanks for asking! Device.SetFlags can also be called from the platform projects. You can find more info on our experimental flags and how to set them [here](https://docs.microsoft.com/xamarin/xamarin-forms/internals/experimental-flags). Hope this helps! :)

**Comment by EmilAlipiev** [comment]
Yes I know but saying  that it must happen before forms.init is wrong or outdated I believe. Forms.init obviously before platform project initialized.
