### ISSUE TITLE
TranslateTo stops working after random time 

### ISSUE THREAD

**Issue by eli191** [xamarin/Xamarin.Forms-api-docs#278]
Hi,

I have a `PancakeView` in my app which I rescale using `ScaleTo` and move using `TranslateTo` on user touch, with length 0.

It works for a few seconds and then stops moving the view. 
Scaling still continues working, but the view doesn't move anymore on iOS. 
On Android, the view moves then evaporates ? (fades out) and it is not visible anymore.

I have another screen with a `CachedImage` which I move also and that reacts in the same way.

I use `Xamarin.Forms 5.0-pre6`

Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80530dfa-7f7a-424f-b438-7d97b17ac4d5
* Version Independent ID: 6cc45f37-df0d-decd-3bb2-d890a86db7b8
* Content: [ViewExtensions.TranslateTo(VisualElement, Double, Double, UInt32, Easing) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.viewextensions.translateto?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/ViewExtensions.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ViewExtensions.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @eli191 - thanks for sharing your experience! Would you mind opening a bug report and filling out the given template [here](https://github.com/xamarin/Xamarin.Forms/issues/new/choose) with more details about your situation (i.e. last working version, reproduction, etc)? Thank you :)

**Comment by eli191** [comment]
Hi @rachelkang will try to do a sample demo as soon as possible.

**Comment by eli191** [comment]
As per you requested, I opened a bug report with reproduction sample [here](https://github.com/xamarin/Xamarin.Forms/issues/13346)

Thanks for your attention

**Comment by rachelkang** [comment]
Thanks @eli191! I'll close this now, but we'll be sure to take a look at the detailed issue you submitted in our Xamarin.Forms repo :)
