### ISSUE TITLE
Download Xamarin.Forms API documentation

### ISSUE THREAD

**Issue by kumar007git** [xamarin/Xamarin.Forms-api-docs#279]
Hello,
This is the page for Xamarin.Forms API documentation (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.dualscreen?view=xamarin-forms).
How can I download or convert this entire Xamarin.Forms API documentation into an offline PDF? Or is this documentation available as a PDF or a HTML help file?

Any help is appreciated.

Thanks

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
