### ISSUE TITLE
Application.Quit() should indicate that it does not work on every platform

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms-api-docs#28]
from https://github.com/xamarin/Xamarin.Forms/issues/3491#issuecomment-411133975:

This feature was added for desktop platforms only ( see #1126). It doesn't apply to mobile platforms. Also not implemented on UWP.

**Comment by mshwf** [comment]
Please add a comment to the method, it's really confusing!

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
