### ISSUE TITLE
Is there documentation detailing the application resource keys available for styling?

### ISSUE THREAD

**Issue by TheCakeMonster** [xamarin/Xamarin.Forms-api-docs#284]
I'm working on a Hybrid Mobile Blazor Bindings application, which uses Xamarin Forms for WPF to host a user interface defined using Blazor components. Note that this type of application doesn't use XAML; instead, a ContentPage is created in C# and after that, all of the UI is created using Blazor components.

I have found it very hard to discover how to style the shell of the application, especially the command bar and the navigation bar (which I turned off, as that was easier.)

Eventually, I stumbled across a StackOverflow answer which indicated that you could add a specially named resource to the Application.Resources collection to apply style to the command bar. However, I can't find a list of the resource keys that can be specified in order to apply styles this way. Does such a document exist? If so, should it be linked to from the Application class page at https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application?view=xamarin-forms

The following are example resource key names you just have to know, or stumble across, to be able to do what you want. I think there would be a lot of benefit to the community if there were a definitive list somewhere - or, if this list exists, for it to be linked to from a number of other places to make it more discoverable.

CommandBarBackgroundColor
CommandBarTextColor

As a slight aside, the fact that you don't use XAML for an application of this type (coming to .NET MAUI in .NET 6) means we could probably do with some example code on how to apply resources to the application's resources dictionary using C#, so that people know how to do what is normally shown in XAML in all of the examples.

**Comment by TheCakeMonster** [comment]
I created an issue about my plight in attempting to change the command bar in the Mobile Blazor Bindings repo. Purely for reference, here is that issue: https://github.com/dotnet/MobileBlazorBindings/issues/359

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
