### ISSUE TITLE
Nested code samples

### ISSUE THREAD

**Issue by MartinZid** [xamarin/Xamarin.Forms-api-docs#46]
You have nested code samples, which breaks the code highlighting. 
They should be separated or merged into one sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567a54fb-4dd3-4bde-ec9f-839311622432
* Version Independent ID: 1849ceed-75cc-d8b1-8f93-8f32c3cf24b3
* Content: [ListView Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/ListView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ListView.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Hi @MartinZid that's actually a rendering bug. Thanks for bringing it to our attention, it should be one single code block. We're investigating how to fix this across a few affected pages.
