### ISSUE TITLE
Platform effects for Xamarin.forms Mac apps

### ISSUE THREAD

**Issue by mdonogma** [xamarin/Xamarin.Forms-api-docs#49]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/introduction

Where is Mac support? Xamarin forms for Mac has been in preview for almost 18 months while porting a demo app I was horrified to find out effects are not supported yet. Help please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99bd4dfe-8006-0e7b-9391-4256dcc13a31
* Version Independent ID: 0398e3bf-27a2-8a37-0537-c1ae9fa0c7fe
* Content: [PlatformEffect&lt;TContainer,TControl&gt; Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformeffect-2?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/PlatformEffect`2.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/PlatformEffect`2.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Hi @mdonogma this is a question for the team - please raise an issue on the [Xamarin.Forms GitHub repo](https://github.com/xamarin/xamarin.forms/issues). You can also review the source code there, and visit the [roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap).
