### ISSUE TITLE
Page content is broken

### ISSUE THREAD

**Issue by bwidemann** [xamarin/Xamarin.Forms-api-docs#51]
There is an error in the page that breaks the sample.
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview?view=xamarin-forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567a54fb-4dd3-4bde-ec9f-839311622432
* Version Independent ID: 1849ceed-75cc-d8b1-8f93-8f32c3cf24b3
* Content: [ListView Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/ListView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ListView.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Thanks @bwidemann, you're right! The code rendering here is broken, we are working on a fix.

Please visit the [ListView docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/) for other examples.

**Comment by bwidemann** [comment]
I discovered afterwards that the code is good on the French version of the same page.
So I guess fixing the English page is merely a matter of copy-paste.

**Comment by conceptdev** [comment]
Glad you found a working copy!
