### ISSUE TITLE
This seam to be required only on UWP projects, not on Android or IOS

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms-api-docs#57]
I have code that looks like this:

```
Task.Run(async() =>
{
   IList<Model> list = await GetListAsync();
   foreach(var model in list)
   {
      //MyList is data bound to ListView.
      // This will work fine on Android and IOS but on UWP, it requires 
      //Device.BeginInvokeOnMainThread wrapping the call below.
      MyList.Add(model);  //MyList is data bound to ListView
   }
});
```

As per comments, it works fine on IOS and Android, but not on UWP.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e06d33-fcc4-e4f8-103c-fb286df48c29
* Version Independent ID: 774d794a-04a4-2d51-07d3-77f20157dfbc
* Content: [Device.BeginInvokeOnMainThread(Action) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
What is your question @dinobu?

**Comment by dinobu** [comment]
> What is your question @dinobu?

Not a question, just a comment on your article here here [https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms)

I find that I need to use BehinInvokeOnMainThread only on UWP in above case.

**Comment by dfoulk** [comment]
@dinobu - There are many cases where Device.BeginInvokeOnMainThread(Action) is necessary on Android and/or iOS. Though we try to limit our usage of this method, it is sometimes needed on each supported platform to display UI elements properly.

**Comment by dfoulk** [comment]
@dinobu I can't tell you the last time I had to use `Device.BeginInvokeOnMainThread(Action)` now that I am familiar with how async/await and Tasks work. It helps a ton- especially when using a bunch of "async/await" and "async Tasks". This is testament to what @MappingSteve said.

I hate when people say this, but in this case I believe it to be true; if you are finding yourself using `Device.BeginInvokeOnMainThread(Action)`, then you are probably manipulating a UI element in the "wrong" place. There are exceptions, of course.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
