### ISSUE TITLE
Needs more description

### ISSUE THREAD

**Issue by tjdennis** [xamarin/Xamarin.Forms-api-docs#58]
You fail to mention that this does not work on iOS or on the Back button on the NavigationPage. It only works for the hardware back button on Android phones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7123c9d-ed66-bba4-6fe1-498a054dc760
* Version Independent ID: 16a9d9a5-27ae-eb60-8a53-ab448c1c0bb4
* Content: [Page.OnBackButtonPressed Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.Page.OnBackButtonPressed?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Page.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Page.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by charlesroddie** [comment]
It also needs to describe what the `bool` does. This page https://forums.xamarin.com/discussion/30910/how-do-you-properly-implement-a-onbackbuttonpressed-override-with-async-functions contains the comment for `true`: "prevent Xamarin.Forms from processing back button".
