### ISSUE TITLE
Released not being called for UWP

### ISSUE THREAD

**Issue by JohnGaby** [xamarin/Xamarin.Forms-api-docs#59]
When running under UWP, if I press a button, I get the Pressed event. If I release the button I get the Released event. However if I press a button then drag off the button and release, I do not get a Released event. I am using the Pressed and Released events to change the appearance of the button. How can I tell that the user has dragged off the button so I can return it to the normal state.  Note that this works correctly under Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17644c74-2666-8de8-c383-06d4e356c49e
* Version Independent ID: a21b8e6d-148c-5759-82bf-ae13af62439e
* Content: [Button.Released Event (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.button.released?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Button.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Button.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by VictorKochetkov** [comment]
This issue also reproducible on Android (Xamarin.Forms)

**Comment by PureWeen** [comment]
Closing this issue on the API docs

Here's a link to the issue on our SDK repository
https://github.com/xamarin/Xamarin.Forms/issues/3310
