### ISSUE TITLE
First Example is not properly formatted

### ISSUE THREAD

**Issue by nosmirck** [xamarin/Xamarin.Forms-api-docs#60]
First example looks like a nested code box inside another code box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d24dee1-929c-ba3b-e555-8451d458ff97
* Version Independent ID: a3cde3a3-d23f-07e8-7249-82024f46e235
* Content: [VisualElement.Resources Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.resources?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Thanks for the feedback, we'll fix it up!

**Comment by lobrien** [comment]
Fixed in bb0d2bd0
