### ISSUE TITLE
Android screenshot is inaccurate

### ISSUE THREAD

**Issue by kmustang** [xamarin/Xamarin.Forms-api-docs#61]
The screenshot on this page shows a "reel" style date picker for Android. It actually uses a calendar style (as is shown on this page: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datepicker).

If it is possible to get the reel-style picker on Android, please make how to do that more clear. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8230342-8a1a-8f6d-c07c-b9c696549eb8
* Version Independent ID: a199786b-523a-7881-21a6-7521034d0802
* Content: [DatePicker Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.datepicker?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/DatePicker.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/DatePicker.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
