### ISSUE TITLE
Mention that it does not include margin height

### ISSUE THREAD

**Issue by Ghasan** [xamarin/Xamarin.Forms-api-docs#63]
The same applies to Width page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c5c0168-baed-5882-9e02-de9dfbc3f716
* Version Independent ID: c635e562-60c8-adc2-a6dc-ee446097f495
* Content: [VisualElement.Height Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.height?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
