### ISSUE TITLE
Clarify how to apply Visual to a whole application

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms-api-docs#65]
Add some instruction to https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual about applying a visual application-wide (such as an implicit style on `Page` or setting the visual on your `Application.MainPage`)

See xamarin/Xamarin.Forms#6063

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
