### ISSUE TITLE
Default animation

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms-api-docs#70]
For `PushAsync(Page)`, what is the default animation? Does it vary by platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760460b4-6ebb-ce40-8a37-a823b2a5b0b4
* Version Independent ID: 4abeb647-d623-1b6b-0d67-3986ddf483ef
* Content: [NavigationPage.PushAsync Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.pushasync?view=xamarin-forms#Xamarin_Forms_NavigationPage_PushAsync_Xamarin_Forms_Page_)
* Content Source: [docs/Xamarin.Forms/NavigationPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/NavigationPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by lobrien** [comment]
Yes, it's the default. In the case of Android, it's the default animation for a `ViewPager` (which I think is a nop). In the case of iOS, it's the default animation of a `UINavigationController`.

**Comment by breyed** [comment]
The documentation should state that. As it is, someone using the overload with the `animated` parameter doesn't know what the behavior will be.
