### ISSUE TITLE
Missing important information.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms-api-docs#74]
Does the method block until the code executes? If the code executes asynchronously, should it be returning a Task so the current code can wait? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e06d33-fcc4-e4f8-103c-fb286df48c29
* Version Independent ID: 774d794a-04a4-2d51-07d3-77f20157dfbc
* Content: [Device.BeginInvokeOnMainThread(Action) Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.begininvokeonmainthread?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/Device.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Device.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Dtyrell** [comment]
I just came here to find out how to wait until an action that I want to run on the main thread had completed.  Is there currently no way to do so?  I feel like making BeginInvokeOnMainThread return an async task would be very useful for improving reliability.

**Comment by lobrien** [comment]
`Device.InvokeOnMainThreadAsync` that returns `Task<T>` is currently in Preview release and using it with standard `async / await` would be the preferred way to asynchronously invoke on the main thread. The current `BeginInvokeOnMainThread` returns immediately; if you cannot work with the preview, Adam Kemp's code at https://forums.xamarin.com/discussion/51720/wait-for-device-begininvokeonmainthread is a good answer (very similar to the implementation code of `InvokeOnMainThreadAsync`). 

API docs updated in https://github.com/xamarin/Xamarin.Forms-api-docs/commit/ebd8c716cc6765ffd265afda9aabcd7cae3d9b33
