### ISSUE TITLE
No code indentation on the code blocks

### ISSUE THREAD

**Issue by TimoSalomaki** [xamarin/Xamarin.Forms-api-docs#80]
Both C# code blocks in the remarks section are missing the proper indentation.

In the markdown file, everything is properly intended so that's not the problem here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb9898d8-e02f-4eaf-6f63-012d6fb2d235
* Version Independent ID: bd6e4d8f-3661-6cf7-530a-baf3e4785c8e
* Content: [AbsoluteLayout Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.absolutelayout?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/AbsoluteLayout.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/AbsoluteLayout.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
