### ISSUE TITLE
IsVisible - Different behavior on Android/IOS vs. UWP

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms-api-docs#85]
Above you say "Setting IsVisible to false will remove the element from the visual tree. The element will no longer take up space in layouts or be eligle to receive any kind of input event."
This however is only true on UWP, not on Android and IOS.  If you have an Entry as IsVisible=False, that entry will still be able to receive focus and input on Android and IOS which is correct behavior as setting to IsVisible to False does not mean the view is not present in visual tree, it is just not visible. 
However, on UWP, that Entry will not be able to receive input nor Focus()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e367c1-186f-129d-f2ec-614289d18f90
* Version Independent ID: 3e93a555-cc22-0fa2-ce85-a30673149a58
* Content: [VisualElement.IsVisible Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.isvisible?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by solomonfried** [comment]
This behavior has caused issues for me since I tend to develop on UWP and then test on iOS and Android. I use IsVisible to create screen popups my placing a control into a Row of a Grid.
Under UWP setting IsVisible to false, causes the popup to disappear and the underlying form receives user input. On iOS and Android, the Form behaves as if it is frozen since all user interaction are trapped by the overlaying 'invisible' form. 
Have you found a way to make it work the same way on all platforms? 
For now, I need to remove the item from the grid, or Move it our of the way ('TranslateTo').
It would be nice if the Material Visual feature in Xamarin 4.0.0 would allow IsVisible=false to behave the same way across platforms.

**Comment by dinobu** [comment]
> This behavior has caused issues for me since I tend to develop on UWP and then test on iOS and Android. I use IsVisible to create screen popups my placing a control into a Row of a Grid.
> Under UWP setting IsVisible to false, causes the popup to disappear and the underlying form receives user input. On iOS and Android, the Form behaves as if it is frozen since all user interaction are trapped by the overlaying 'invisible' form.
> Have you found a way to make it work the same way on all platforms?
> For now, I need to remove the item from the grid, or Move it our of the way ('TranslateTo').
> It would be nice if the Material Visual feature in Xamarin 4.0.0 would allow IsVisible=false to behave the same way across platforms.

Unfortunately, Xamarin requires so many hacks to work with 
In my case an invisible entry field will not receive focus, so instead some other view will get it.  For example, I do scanning, so that invisible entry is used to scan a barcode and process it.  But the problem I face is that if I tap on a button, then scan will trigger that button even since focus stayed on that button instead to be moved to Entry.  I resolved my problem by making the Entry very small (0px) and visible on UWP, while making it invisible on Android, IOS (but here I had to set its size to 1px since 0px would not receive focus.  So, happy hacking with Xamarin

**Comment by bendincuta** [comment]
Did you guys find any solution on this issue?
On iOS and Android, in my case, the control that has IsVisible set to false, gets hidden but if I have anything below it, it's frozen. It seems to me like the visibility part works as expected but not the "The element will no longer take up space in layouts" part.

**Comment by PureWeen** [comment]
I'm going to close this issue here since this is already logged here https://github.com/xamarin/Xamarin.Forms/issues/6536

@bendincuta if you could add details to the above issue that would be helpful
