### ISSUE TITLE
Confuse

### ISSUE THREAD

**Issue by Laael** [xamarin/Xamarin.Forms-api-docs#88]
PushAsync(Page) presents a modal page but PushAsync(Page, Boolean) presents a simple page. It correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 760460b4-6ebb-ce40-8a37-a823b2a5b0b4
* Version Independent ID: 4abeb647-d623-1b6b-0d67-3986ddf483ef
* Content: [NavigationPage.PushAsync Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.pushasync?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/NavigationPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/NavigationPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rachelkang** [comment]
Hi, @Laael - apologies for the confusion, and thanks for submitting this issue!
PushAsync() pushes any page (as long there's a NavigationPage somewhere in the stack) and PushModalAsync() pushes any page modally (from anywhere). In both cases, the second Boolean argument dictates whether or not the push is animated. We'll fix these docs for PushAsync() shortly, and you can find the docs for PushModalAsync() [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.inavigation.pushmodalasync?view=xamarin-forms)
