### ISSUE TITLE
Why not having Keyboard.None to show no keyboard at all?

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms-api-docs#89]
There are plenty cases where this would be useful
- I am making my own keyboard and I dont want the softkeyboard to pop up when Entry is focused
- I am scanning into this field and I dont want softkeyboard to show

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964097f9-62ef-eead-bee7-f7a5ec2ecc90
* Version Independent ID: 8b449255-133d-c04d-9f17-fe9b0daaf1e5
* Content: [Keyboard Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.keyboard?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Keyboard.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Keyboard.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
@dinobu The idea may have merits, but this isn't the right repo to open the issue. You probably want to post this in https://github.com/xamarin/Xamarin.Forms/issues.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
