### ISSUE TITLE
How is this different than Entry?

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms-api-docs#90]
How is this different than Entry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fe5127-c0bf-cfd5-5834-d6cbdbfd64d2
* Version Independent ID: bf783ff2-8c36-9707-8bc9-0c391afec643
* Content: [SearchBar Class (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.searchbar?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/SearchBar.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/SearchBar.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
@dinobu SearchBar also provides Search and Cancel buttons, and a SearchCommand. And it maps to the various Search controls on each platform (as opposed to Entry, which maps to TextBox, EditText, etc.)

**Comment by dinobu** [comment]
> @dinobu SearchBar also provides Search and Cancel buttons, and a SearchCommand. And it maps to the various Search controls on each platform (as opposed to Entry, which maps to TextBox, EditText, etc.)

Would be nice the documentation provides bit more detail, better example, use with XAML, better visual showing live graphic rather than just view of initial image, more explanation etc.  Even though it is just a glorified Entry, the doc should be more revealing and explanatory than what it is now

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
