### ISSUE TITLE
Remark is inaccurate

### ISSUE THREAD

**Issue by kmustang** [xamarin/Xamarin.Forms-api-docs#94]
For the record, on Android at least, unfocusing the control does NOT call the Completed event. It looks like it's only called when pressing the "Done" button on the keyboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3caddb8-c64a-35a7-bc31-f2b2533c4788
* Version Independent ID: 968674b4-7c3f-11e9-ca7a-6c30f02a4dc9
* Content: [Editor.Completed Event (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.editor.completed?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/Editor.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Editor.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
