### ISSUE TITLE
No doc

### ISSUE THREAD

**Issue by dotMorten** [xamarin/Xamarin.Forms-api-docs#95]
All these members says they should only be used by platform renderers. But if you are a person trying to build a platform renderer, there's no useful doc on this class. Please provide more information here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d898bf0-ba79-9f30-7bcc-77095d5319cf
* Version Independent ID: 83607085-94c4-49c8-e834-ff9818f9bdb9
* Content: [IVisualElementController Interface (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.IVisualElementController?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/IVisualElementController.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IVisualElementController.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
