### ISSUE TITLE
And what does the return value do?

### ISSUE THREAD

**Issue by dcarapic** [xamarin/Xamarin.Forms-api-docs#96]
It is not clear what returning true/false does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86d70014-abc3-ced9-6f3a-c7d21b9afcd6
* Version Independent ID: d0330e76-7596-77f2-bc08-712c8fc999ee
* Content: [NavigationPage.OnBackButtonPressed Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.onbackbuttonpressed?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/NavigationPage.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/NavigationPage.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jcmanke** [comment]
For the record, this is my understanding how it works, as of January 2015: 

> If you return true from then you will not go back to the previous page, unless you also call the base method in your override.

https://forums.xamarin.com/discussion/comment/95162/#Comment_95162

**Comment by SittenSpynne** [comment]
How many months does it take to get a feature documented?
