### ISSUE TITLE
IsEnabled doesn't apply to children as any XAML developer would expect

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms-api-docs#97]
Setting IsEnabled to false has no effect on children elements. This is definitely against any other XAML philosophy (WPF, WP8, UWP) so I think documentation should clearly state this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bb5f557-1afd-1e2d-4f47-acf8dbaaa482
* Version Independent ID: 96644a88-dd66-46a2-eb11-bcd13308cb9b
* Content: [VisualElement.IsEnabled Property (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.isenabled?view=xamarin-forms)
* Content Source: [docs/Xamarin.Forms/VisualElement.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/VisualElement.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by derekantrican** [comment]
+1

Apparently this used to be a bug with Xamarin but was marked as "Resolved": https://xamarin.github.io/bugzilla-archives/43/43007/bug.html

Now I'm seeing it again: setting the `IsEnabled` property of a `StackLayout` does not disable the child controls

**Comment by PureWeen** [comment]
Is looks like there have been a couple issues logged about this on the Xamarin.Forms github

https://github.com/xamarin/Xamarin.Forms/issues/9121

Can you add some information to the above issue or create a new one with a repro of what you're seeing?
