### ISSUE TITLE
SearchBar documentation 

### ISSUE THREAD

**Issue by dbnex14** [xamarin/Xamarin.Forms-api-docs#98]
Would be nice the SearchBar documentation provides bit more detail, better example, use with XAML, better visual showing live graphic rather than just view of initial image, more explanation etc. Even though it is just a glorified Entry, the doc should be more revealing and explanatory than what it is now

**Comment by rachelkang** [comment]
Hi, @dbnex14 - you might be able to find the more detailed information you're looking for here: https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/searchbar

with demos linked at the bottom of the page: https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-searchbardemos/

I hope this is helpful! But if not, let us know :)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any issues with the .NET MAUI API docs should be opened in that repository.
